version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_test
    restart: always
    ports: 
      - 27017:27017
    networks:
      - stack-network
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo_express_test
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example 

networks:
  stack-network:
    driver: bridge